"""add cooking time

Revision ID: 777ce7844aa3
Revises: 9e91f4e1d13c
Create Date: 2022-06-21 17:57:38.651526

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "777ce7844aa3"
down_revision = "9e91f4e1d13c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipe", sa.Column("cooking_time_min", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipe", "cooking_time_min")
    # ### end Alembic commands ###
