"""empty message

Revision ID: 9e91f4e1d13c
Revises: 808557f08747
Create Date: 2022-06-21 17:19:45.565454

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "9e91f4e1d13c"
down_revision = "808557f08747"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("recipe", "carb_gram", existing_type=sa.FLOAT(), nullable=True)
    op.alter_column("recipe", "protein_gram", existing_type=sa.FLOAT(), nullable=True)
    op.alter_column("recipe", "fat_gram", existing_type=sa.FLOAT(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("recipe", "carb_gram", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("recipe", "protein_gram", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("recipe", "fat_gram", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
