"""Source as text

Revision ID: 9f8ede5642b6
Revises: 777ce7844aa3
Create Date: 2022-09-19 12:13:30.699059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "9f8ede5642b6"
down_revision = "777ce7844aa3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recipe",
        "source",
        existing_type=mysql.VARCHAR(charset="utf8mb4", collation="utf8mb4_unicode_ci", length=64),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recipe",
        "source",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(charset="utf8mb4", collation="utf8mb4_unicode_ci", length=64),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
